Notification list
Elly-G/IntellST pull request #30
Opened 2020-08-10 21:32 UTC by Elly-G

add notification list

2020-08-12 14:32 UTC, andreikojusko requested changes

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/DTO/IdentifiedCaseDTO.php
> +use phpDocumentor\Reflection\Types\Integer;
not needed

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Entity/IdentifiedCase.php
> +use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
is it used?

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +        $period = strval($day);
not needed

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +    public function showNewIdentifiedCase(int $day, float $temperature)
why "show"? isn't it "get"? same in other "show" methods

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +        $period = strval($day);
not needed

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +            ->Where('IdentifiedCase.allowEntrance > :date')
"where" (lowercase w)

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +        $data = new \DateTime();
`$date`

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +//    }
is this code needed?

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +    public function allowEntrance(string $uuid)
isEntranceAllowed

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +            ->execute();
why "execute" and not "getResult"?

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +            ->execute();
why "execute" and not "getResult"?

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +            ->execute();
why "execute" and not "getResult"?

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +    public function returnAttempt(int $day, float $temperature, string $uuid)
probably, "getReturnAttempts"

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +            ->Where('IdentifiedCase.firstDate > :date')
lowercase "w"

2020-08-12 14:32 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +    public function showReturnAttempt(string $uuid, $data)
$date

2020-08-14 13:30 UTC, andreikojusko requested changes

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Entity/Enterprise.php
> +    private $identifiedCase;
$identifiedCases (multiple)

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/DTO/IdentifiedCaseDTO.php
> +
empty line not needed

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +            ->execute();
why "execute" and not "getResult"?

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Services/UserHandler.php
> +    public function getList(): UserDTO
why getList returns single user? method should be named `getCurrentUser`

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Transformer/EnterpriseTransformer.php
> +
extra line

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Transformer/IdentifiedCaseTransformer.php
> +        $this->em = $em;
looks like `$this->em` is never used

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Transformer/IdentifiedCaseTransformer.php
>          return $identifiedCase;
blank line before return please

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Transformer/UserTransformer.php
>          return $userDTO;
blank line before return please

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Services/IdentifiedCaseHandler.php
> +    public function getIdentifiedCase(): array
`getIdentifiedCases` (multiple)

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Services/IdentifiedCaseHandler.php
> +        return $arr;
blank line before return

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Services/IdentifiedCaseHandler.php
> +    private function returnUserEnterprise(UserDTO $dto): EnterpriseDTO
`getUserEnterprise`
Also, why have 2 methods? Isn't it simplied to have 1 method that return EnterpriseDTO by enterprise ID? You can have just `getEnterprise(int $id)`

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Services/IdentifiedCaseHandler.php
> +        $data = $this->returnUserEnterprise($user)->restrictionPeriod;
not need to make 2 requests to `returnUserEnterprise`
```
$dto = $this->returnUserEnterprise($user);
```
then use `$dto->temperature`

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Services/IdentifiedCaseHandler.php
> +        $data = $this->returnUserEnterprise($user)->restrictionPeriod;
`$data` isn't a good name. If it is a number of days, then `$days` if it is DateTime, then `$date`

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Services/IdentifiedCaseHandler.php
> +        $users = $this->identifiedCaseRepository->getNewIdentifiedCase($data, $temperature);
`$users` or `$cases`?

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Services/IdentifiedCaseHandler.php
> +        $day = $this->getEnterprise($dto)->restrictionPeriod;
don't call `getEnterprise` twice

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Services/IdentifiedCaseHandler.php
> +    public function getReturnAttempts(IdentifiedCaseDTO $dto): bool
why `getReturnAttempts` if it returns a boolean? `it should be `isReturnAttempt`

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Services/IdentifiedCaseHandler.php
> +        }
why do you need all this code? no need in transformations at all
```
$list = $this->identifiedCaseRepository->getReturnAttempts($day, $temperature, $uuid);

return !(empty($list));
```

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Services/IdentifiedCaseHandler.php
> +    public function entranceAllowed(IdentifiedCaseDTO $dto): bool
`isEntranceAllowed`

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Services/IdentifiedCaseHandler.php
> +        }
```
$list = $this->identifiedCaseRepository->entranceAllowed($uuid);

return !(empty($list));
```

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Services/IdentifiedCaseHandler.php
> +    public function getReturnAttempt(): array
please review naming, calls, logic as in comments for other methods

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +    public function getReturnAttempt(string $uuid, $data)
`getReturnAttempts` (multiple), return type, `$date`

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +    public function getReturnAttempts(int $day, float $temperature, string $uuid)
missing return type

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +        $date->modify('-1 day');
why 1 day???

2020-08-14 13:30 UTC, andreikojusko commented on intellst-api/src/Repository/IdentifiedCaseRepository.php
> +    public function entranceAllowed(string $uuid)
name isn't good, but I can't suggest better name as I don't have any idea what should this method do, also missing return type

2020-08-19 08:32 UTC, Elly-G commented on intellst-api/src/Transformer/IdentifiedCaseTransformer.php
> +        $this->em = $em;
is used in transformDTOToEntity 
` $enterprise = $this->em->getRepository(Enterprise::class)->find($dto->enterprise); `

2020-08-19 11:37 UTC, merged